load predMetabolismFromGCP.mat;
cormat = corr(X, Y);
redbluecmap = imresize(redbluecmap, [1000, 3]); redbluecmap = min(max(redbluecmap, 0), 1);
metabolites = strrep(metabolites, '_', ' ');
heatmap(cormat', 'colormap', redbluecmap, ...
        'YData', metabolites, ...
        'XData', markers(:, [1:18, 20:38, 40:end]))
clustergram(cormat', ...
            'RowLabels', metabolites, ...
            'ColumnLabels', markers(:, [1:18, 20:38, 40:end]), ...
            'RowPdist', 'correlation', ...
            'ColumnPdist', 'correlation')
        
tmp = (cormat > 0.15 | cormat < -0.15);
tmp2 = any(tmp, 1);
tmp3 = cormat(:, tmp2)
tmpmet = metabolites(tmp2)

metabolic_subset = [2, 3, 4, ...        % H3K4
                    6, 7, 8, 9, ...     % H3K9
                    23, 27, 30, 32, ... % H3K27
                    20, 21, 22, ...     % H3K36
                    39, 40];            % H3K79
tmp3 = tmp3(metabolic_subset, :);
tmp4 = markers(:, [1:18, 20:38, 40:end])
tmp5 = tmp4(metabolic_subset)

heatmap(tmp3', 'colormap', redbluecmap, ...
        'YData', tmpmet, ...
        'XData', tmp4(metabolic_subset))
clustergram(tmp3', ...
            'RowLabels', tmpmet, ...
            'ColumnLabels', markers(:, [1:18, 20:38, 40:end]), ...
            'RowPdist', 'correlation', ...
            'ColumnPdist', 'correlation')
        
boxplot(X(:, metabolic_subset))