---
title: "Process CCLE RNASeq dataset"
output: html_notebook
---

# Summary
This notebook maps the gene identifiers to Entrez IDs.

```{r}
install.packages("tidyverse")
install.packages("readxl")

library(readxl)
```

Let's also load up Bioconductor and the mapping database:

```{r}

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install(c("hgu133plus2.db", "org.Hs.eg.db"))
library(hgu133plus2.db)
library(org.Hs.eg.db)

```

```{r}

filename = "~/Data/RNASeq/CCLE/Processed_CCLE_Effect.csv"
effect = read.csv(filename)

filename = "~/Data/RNASeq/CCLE/Processed_CCLE_Pvalue.csv"
pvalue = read.csv(filename)

ensembl = sub("\\.\\d+$", "", effect[, 1])

# Create a map of the probes to Entrez and gene symbols
map = select(hgu133plus2.db,
             keytype="ENSEMBL",
             keys=ensembl, 
             use.names=FALSE, 
             columns = c('ENTREZID', 'SYMBOL')
             )

effect[, 1] = ensembl
pvalue[, 1] = ensembl

effect = merge(map, effect, by.x='ENSEMBL', by.y='genes')
pvalue = merge(map, pvalue, by.x='ENSEMBL', by.y='genes')

install.packages("writexl")
library("writexl")
filename = "~/Data/RNASeq/CCLE/Mapped_Processed_CCLE.xlsx"
sheets = list("EffectSize"=effect, "PValue"=pvalue)
write_xlsx(sheets, filename)


# Get gene identifiers
geneIDs = df[, c("ENSEMBL", "ENTREZID", "Gene Name")]


# Get raw data
drops = c("ENSEMBL", "ENTREZID", "SYMBOL", "Gene Name")
df = df[, -c(1:4)]

# Get Tissue and Cell Line names
cols = colnames(df)
cols = cols[5:length(cols)]
cols = as.data.frame(cols)

library(tidyr)
cols = separate(data=cols, col=cols, into=c("Tissue", "Cell Line"), sep=", ")
```

Save all data as Excel file

```{r}
install.packages("xlsx")
library("xlsx")

filename = ""

write.xlsx(geneIDs, filename, 
           sheetName="GeneID",
           col.names=TRUE, row.names=FALSE)

write.xlsx(df, filename, 
           sheetName="Eset", 
           col.names=TRUE, row.names=FALSE)

write.xlsx(cols, filename, 
           sheetName="CellIDs",
           col.names=TRUE, row.names=FALSE)

```